version: '3'

services:
    saver-transit:
        image: pravahio/py-pravah:latest
        volumes:
            - "./transit/transit.py:/usr/src/pravah/transit.py"
            - "./db.py:/usr/src/pravah/db.py"
        environment:
            - PRAVAH_DB_USERNAME=${PRAVAH_DB_USERNAME}
            - PRAVAH_DB_PASSWORD=${PRAVAH_DB_PASSWORD}
            - PRAVAH_DB_HOST=${PRAVAH_DB_HOST}
            - PRAVAH_API_KEY=${PRAVAH_API_KEY}
        command: python -u transit.py
        network_mode: "host"
    
    saver-atc:
        image: pravahio/py-pravah:latest
        volumes:
            - "./atc/atc.py:/usr/src/pravah/atc.py"
            - "./db.py:/usr/src/pravah/db.py"
        environment:
            - PRAVAH_DB_USERNAME=${PRAVAH_DB_USERNAME}
            - PRAVAH_DB_PASSWORD=${PRAVAH_DB_PASSWORD}
            - PRAVAH_DB_HOST=${PRAVAH_DB_HOST}
            - PRAVAH_API_KEY=${PRAVAH_API_KEY}
        command: python -u atc.py
        network_mode: "host"
